document.writeln('<div class="header">');
document.writeln('	<div class="headerIn">');
document.writeln('        <div class="headerLink">');
document.writeln('            <a href="#"onClick="$(\'#login\').dialog(\'open\');return false">登录</a>|');
document.writeln('            <a href="#" onClick="$(\'#identity\').dialog(\'open\');return false">注册</a>|');
document.writeln('            <a href="#">设为首页</a>|');
document.writeln('            <a href="#">加入收藏</a>');
document.writeln('        </div>');
document.writeln('        <div class="clearfix">');
document.writeln('        	<div class="headerLogo"></div>');
document.writeln('            <div class="headerInteration">');
document.writeln('                <span class="headerFeedback">意见反馈</span>');
document.writeln('                <span class="headerTel">客服热线：400-067-1909</span>');
document.writeln('            </div>');
document.writeln('        </div>');
document.writeln('        <ul class="nav clearfix">');
document.writeln('        	<li class="current"><a href="default.html">首页</a></li>');
document.writeln('            <li><a href="#">应用</a></li>');
document.writeln('            <li><a href="#">教师</a></li>');
document.writeln('            <li><a href="#">课程</a></li>');
document.writeln('            <li><a href="#">素材</a></li>');
document.writeln('            <li><a href="#">文章</a></li>');
document.writeln('        </ul>');
document.writeln('    </div>');
document.writeln('</div>');